.travis.yml, openwisp_users/models.py
This file not being present is breaking the Travis checks on django>=2.0. Probably generated on adding compatibility to django>=2.0
=> [migrations] Fixed django 2.0/1.11 conflict in migration and added checks to travis

runflake8
Fixed: Travis builds fail due to flake8 error on setup.py.
=> [ci] Fixing Travis Build

openwisp_users/tests/test_admin.py, openwisp_users/tests/utils.py
Added `TestBasicUsersIntegration`, which we can use in `openwisp-radius` to perform a basic integration.
Related to https://github.com/openwisp/openwisp-radius/issues/1
=> [tests] Added TestBasicUsersIntegration

openwisp_users/admin.py, openwisp_users/tests/test_admin.py
This code  effectively implement multitenancy login for `OrganizationOwnerAdmin` and `OrganizationUserAdmin` and adds tests  for  the same. 
Closes #46
=> Makes OrganizationOwner and OrganizationUser admins multi-tenant

openwisp_users/migrations/0007_unique_email.py, openwisp_users/models.py, openwisp_users/tests/test_admin.py, openwisp_users/tests/test_models.py
NULL does not trigger the UNIQUE constraint so we
can allow the system to have users without email
(for users automatically generated by the radius module)
Related to #28.
=> [models] Email: allow NULL but set UNIQUE constraint #28

openwisp_users/admin.py, openwisp_users/tests/test_admin.py, requirements-test.txt
log the exception sendmail raised during
user creation with invalid email so that
users are created even with invalid email.
Added a mock test to mimic the exception
raised during user creation.
Added mock to requirements-test.txt
Fixes openwisp#72
=> [admin] Server Error (500). openwisp#72

openwisp_users/tests/test_admin.py
This traceback is being diplayed when validating whether the app throws error for BAD email address unnecessarily. 
`smtplib.SMTPSenderRefused: (501, '5.1.7 Bad sender address syntax', 'test_name@test_domain')`
=> [enhancement] Remove unnecessary traceback from being displayed

openwisp_users/admin.py, openwisp_users/tests/test_admin.py
It is but normal that a superuser should able to
delete any object including organizationuser.
Thus, I fixed the issue by updating the
has_delete_permision of organizationuser to
return True for superusers
Fixes #110
=> [admin] Superuser can't delete a regular user #110

README.rst, openwisp_users/admin.py, openwisp_users/apps.py, openwisp_users/base/models.py, openwisp_users/multitenancy.py, openwisp_users/tests/test_models.py, openwisp_users/tests/utils.py
Follow up to #121.
Closes #107.
@PabloCastellano I added some improvements and updated the code of openwisp-users to use the new method, this wasn't done in #121.
=> [helpers] Organization membership related methods #107

openwisp_users/base/models.py, openwisp_users/tests/test_models.py
Fixed the issue by cleaning phone numbers to ensure that empty
phone numbers are set to None.
Fixes #141
=> [bug] empty phone number triggers unique validation error #141

openwisp_users/apps.py, openwisp_users/tests/test_admin.py, openwisp_users/utils.py
`from .utils import logger` was importing from a file
which imported concrete models, thing which breaks
the application startup when using it with other modules.
=> [fix] Fixed apps logger

openwisp_users/tests/test_admin.py
Removed occurrences where tests were asserting for
"error" string instead of "Please correct the error below."
**EDIT**: I have assumed it is looking for this error message.
=> [refactor] Removed ambiguous test assertions

README.rst, openwisp_users/base/models.py, openwisp_users/tests/test_models.py
Allow passing an UUID or str to the membership helpers, which will
be interpreted as organization primary key.
This is useful in those cases in which building the organization
instance requires generating an extra DB query: passing
obj.organization_id instead of obj.organization will result
in less queries being executed.
=> [chores] Allow passing a string or uuid to the membership helpers

openwisp_users/base/models.py, openwisp_users/tests/test_models.py
Fixed issue by preventing org owners from been downgraded.
Fixes #166
=> [fix] OrganizationOwner shouldn't be allowed to be is_admin=False #166

openwisp_users/settings.py
Removed all the typographic errors for 0.5 release.
Also updated openwisp-utils to 0.7.0 in requirements.txt and
requirements-test.txt
Fixes #194
=> [change] Removed typographic error for backward compatibility for openwisp-users 0.5 #194

openwisp_users/base/models.py, openwisp_users/tests/test_models.py
Removed organizations_pk method from AbstractUser class
of openwisp_users.base.models.py.
Reason - User.organizations_pk is deprecated in favor of
User.organizations_dict and will be removed in a
future version
Fixes #197
=> [deprecated] Removed User.organizations_pk #197

openwisp_users/multitenancy.py, openwisp_users/tests/test_admin.py, tests/testapp/admin.py, tests/testapp/models.py
=> [admin] Change empty org label #171

openwisp_users/tests/test_admin.py, tests/testapp/tests/test_admin.py
The test "test_organization_default_label" depends on a test app
which is not part of openwisp-users, therefore this test should
be shipped in the test app rather than openwisp-users, because
the tests of openwisp-users are imported and re-run in other
modules as integration tests, which test_organization_default_label
was breaking.
@Purhan see :point_up:  and https://github.com/openwisp/openwisp-radius/runs/1628664181.
=> [fix] Fixed test_organization_default_label breaking integration tests

README.rst, openwisp_users/templates/admin/login.html, openwisp_users/tests/test_admin.py, tests/openwisp2/settings.py
Mention that it's now possible to login using
the email or the phone number (provided the
authentication backend is correctly set as
indicated in the README).
Added also a test for the features of the custom
login.html admin template.
=> [chores] Updated admin login template username label

README.rst, openwisp_users/settings.py, tests/openwisp2/settings.py
Set the default value of USERS_AUTH_API in settings.py to true.
Updated the readme.
Closes #203
=> [change] Turn on API by default #203

.travis.yml, openwisp_users/accounts/templates/account/login.html, tests/openwisp2/settings.py, tests/testapp/tests/test_admin.py
Fixed 500 internal server error in /accounts/login/ if
allauth.socialaccount is not in INSTALLED_APPS.
Closes #218
=> [fix] Fixed template exception if social account app not enabled #218

README.rst, openwisp_users/api/mixins.py, tests/testapp/serializers.py, tests/testapp/tests/test_filter_classes.py, tests/testapp/urls.py, tests/testapp/views.py
=> [fix] Fix AttributeError for filter classes #229

openwisp_users/admin.py, openwisp_users/tests/test_admin.py
- Added a test to check the response status on navigating to a non-existing user change page
- Handled exceptions for an invalid UUID and a non-existing user
Fixes #228
=> [fix] Fixed - Exception raised on opening non existing user ID #228

openwisp_users/base/models.py, openwisp_users/tests/test_admin.py
[RFC 5321](https://tools.ietf.org/rfc/rfc5321.txt) states that the `user` in `user@hostname` of an email format is case-sensitive. `USER@example.com` and `user@example.com` are therefore different email addresses (the domain is case-insensitive).
- Overrode the save method of the `AbstractUser` model to make the email lowercase.
- Added a test to check that email is lowered.
- Added a test to ensure that an Integrity error is raised if a new user is created with an existing mail but different case.
- Modified `UserCreationForm`to check if the case-sensitive mail already exists.
Fixes #227
=> [change] Make email lowercase when adding new user #227

README.rst, openwisp_users/admin.py, tests/openwisp2/settings.py
Latest version of DRF changed Token to TokenProxy.
Let's always unregister it (also during development) to
keep consistency across all openwisp modules.
=> [change] Always unregister restframework.authtoken TokenProxy model

CHANGES.rst, README.rst, openwisp_users/backends.py, openwisp_users/settings.py, openwisp_users/tests/test_admin.py, openwisp_users/tests/test_backends.py, openwisp_users/tests/utils.py
- Added phone number parsing to the authentication backend.
The value inserted by users as their idenifier is parsed with ``phonenumbers``
library to understand if it's a phone number, in which case the phone number
lookup is given priority.
This also allows recognizing the phone number if it contains additional
characters like spaces, dashes or dots.
- If any international prefix is specified in the setting
``OPENWISP_USERS_AUTH_BACKEND_AUTO_PREFIXES``, the authentication backend
tries prepending the listed prefixes when parsing numbers, so that users
can authenticate by typing only their national phone number.
Closes #245.
=> [feature] Recognize phone numbers in authentication backend #245

README.rst, openwisp_users/api/permissions.py, tests/testapp/__init__.py, tests/testapp/tests/test_permission_classes.py, tests/testapp/urls.py, tests/testapp/views.py
=> [feature] Implemented view permissions by extending `DjangoModelPermissions` class #249

README.rst, openwisp_users/apps.py, openwisp_users/base/models.py, openwisp_users/tests/test_models.py
This code was introduced because of a misunderstanding.
It's not only not necessary but also buggy, better remove it and
use the permission helpers provided by Django.
Closes #266
=> [change!] Removed custom permission helpers #266

README.rst, openwisp_users/api/mixins.py, openwisp_users/api/permissions.py, tests/testapp/tests/test_permission_classes.py
Updated API permissions classes to allow organization managers and
organization owners to view shared objects.
Related to #238
=> [change/api] Organization managers and owners can view shared objects #238

requirements-test.txt
Removed coveralls because it's defined in openwisp-utils.
=> [tests] Updated test deps

openwisp_users/apps.py, openwisp_users/tests/test_api/test_api.py, openwisp_users/tests/test_models.py
Invalidate user's organizations cache, if
OrganizationUser.user or OrganizationOwner.organization_user field are changed.
Fixes #327
=> [fix] Fixed user's organization cache invalidation #327

openwisp_users/multitenancy.py
- MultitenantOrgFilter: use all lowercase titles for consistency
- MultitenantRelatedOrgFilter: avoid having to define field_name and title each time
=> [chores] Minor improvements to organization filters

.gitignore
- When running coverage testing, it creates `.coverage.*` files, this change will exclude them from git.
=> [chores] Added `.coverage.*` files to `.gitignore`

openwisp_users/api/serializers.py, openwisp_users/tests/test_api/test_api.py
- Added `org_id` to the validation when an organization already exists with the given slug.
- Added tests.
Closes #329
=> [change] Added `org_id` to the validation of organization endpoint #329

tests/openwisp2/settings.py
- While working on https://github.com/openwisp/openwisp-users/pull/334, I discovered that the openwisp custom admin theme is not visible on browsable API webpages; see below: 
=> [fix] Fixed browsable api custom theme

openwisp_users/admin.py
Unregister model admins only if needed to avoid errors when other modules import openwisp_users.admin.
=> [fix] Fixed possible admin unregistration failures

README.rst, openwisp_users/api/filters.py, openwisp_users/api/mixins.py, tests/openwisp2/settings.py, tests/testapp/__init__.py, tests/testapp/admin.py, tests/testapp/migrations/0003_multitenancy.py, tests/testapp/migrations/__init__.py, tests/testapp/models.py, tests/testapp/tests/test_filter_classes.py, tests/testapp/views.py
=> [feature] Added multitenant capablities to django-filters #346

openwisp_users/multitenancy.py, openwisp_users/tests/test_admin.py
Without this patch it is possible that the system will return multiple identical results for a staff user who manages multiple orgs.
Fixes #324.
=> [fix] Fixed bug in UserAdmin when staff user manages multiple orgs

README.rst, openwisp_users/management/commands/export_users.py, openwisp_users/settings.py, openwisp_users/tests/test_commands.py
=> [feature] Added command line utility to export users #355

openwisp_users/base/models.py, openwisp_users/tests/test_models.py
since this project uses 'add_user' method of 'django-organizations' package, I catched the specific integrity error so that I don't interfere with the imported package internals.
Fixes #360
=> fix: Organization.add_user INTEGRITY error

README.rst, openwisp_users/admin.py, openwisp_users/apps.py, openwisp_users/settings.py, tests/openwisp2/settings.py
If OrganizationUserAdmin is disabled, `OrganizationOwnerInline` was loading a select with all the users in the DB, which doesn't work on large databases.
This change enables this admin page by default and avoids loading the `OrganizationOwnerInline` if `OrganizationUserAdmin` is disabled.
=> [change] Enable OrganizationUserAdmin by default

openwisp_users/base/models.py, openwisp_users/tests/test_models.py
The `password_updated` field can be `None`, so trying to perform an addition on it before ensuring the value is not `None` can lead to uncaught exceptions, this patch fixes this issue.
=> [fix] Fix has_password_expired when password_update is None

README.rst, openwisp_users/backends.py, openwisp_users/tests/test_backends.py
This fix allows users of countries which use leading zeros in their national phone numbers to authenticate successfully by using the version of their number with the leading zero, which without this patch fails to be recognized.
=> [fix] Support phone numbers with leading zero in auth backend

openwisp_users/accounts/templates/account/password_not_required.html, openwisp_users/accounts/views.py, openwisp_users/tests/test_accounts.py
Users registered with social login would not have a password set. When they access the password change page, a message would be should to they users that they do not need to change password.
Closes #369
=> [fix] Users registered with social login cannot set password #369

openwisp_users/apps.py, openwisp_users/tasks.py, openwisp_users/tests/test_admin.py, openwisp_users/tests/test_api/test_api.py, openwisp_users/tests/test_models.py
When the status ( is_active ) of an organization changes it now invalidates the cache of all the organizationsusers.
Fixes https://github.com/openwisp/openwisp-users/issues/357.
=> [fix] Invalidate org membership cache when organization is_active flag is changed #357

openwisp_users/tests/test_admin.py, openwisp_users/tests/utils.py, tests/testapp/tests/mixins.py, tests/testapp/tests/test_views.py
Base test classes were quite messed up.
With this change, redundancy is reduced and it should be easier to read the base test methods.
=> [tests] Reorganization and clean up of base test classes

openwisp_users/multitenancy.py, tests/testapp/tests/test_admin.py
Organization admins should not be able to create objects that are shared between different organizations.
=> [fix] Don't allow organization admin to created shared object

requirements.txt
Without the extra packages, the user wouldn't be able to use social account providers out of the box.
=> [deps] Added additional socialaccount dependencies for django-allauth

CHANGES.rst, openwisp_users/__init__.py, requirements-test.txt, requirements.txt
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
---
Check the full commit history: https://github.com/openwisp/openwisp-users/compare/1.0.0...450d41cc265cf4727738fba4aa9bb00432b26007
=> 1.1.0 release
