README.rst

Add some missings steps and information into the README integration section to make it work more fluently for new users

update readme integration section

---

openwisp_users/admin.py
openwisp_users/tests/test_admin.py

[admin] Fixed Integrity error if trying to change email that exists #23

---

.travis.yml
openwisp_users/tests/test_admin.py

Added support for django 2.1 rc.

[requirements] Added support for django 2.1 rc

---

.travis.yml
requirements-test.txt
runcheckmigration

Include tests for checking if the migration file has a descriptive name, if the file has default name, fail ci.

[qa] Include migration file name test

---

.travis.yml
requirements-test.txt
runflake8
runisort
setup.cfg

[qa] cleanup runflake8 and runisort  https://github.com/openwisp/openwisp-users/issues/59
Closes https://github.com/openwisp/openwisp-users/issues/59

[qa] cleanup runflake8 and runisort

---

.travis.yml

[qa] Add message check commit #61

---

openwisp_users/templates/admin/login.html
tests/settings.py

[admin] Move custom login form from openwisp-controller #33

---

openwisp_users/admin.py
openwisp_users/multitenancy.py
openwisp_users/tests/test_admin.py

But, I have serious concerns regarding the `runtests.py`, even after adding the new test function, number of tests didn't change, and to test the problem with test functions further, I deliberately did things to fail test like putting a particular item in both `visible` and `hidden` arguments of the `_test_multitenant_admin` function. I'll open an  issue for the same. 
closes #34

removed the query_set() function from UserAdmin and moved logic to multitenancy

---

openwisp_users/migrations/__init__.py

[bug] Fixes Initial migration error #77

---

openwisp_users/tests/test_admin.py

[bug] fix broken tests #79

---

openwisp_users/models.py
openwisp_users/tests/test_models.py

[ux] Add organization owner validation #76

---

openwisp_users/mixins.py
tests/testapp/models.py
tests/testapp/tests.py

Improves `_validate_org_reverse_relation` added by @NoumbissiValere in #70. 
Closes #70.

Improve _validate_org_reverse_relation

---

openwisp_users/admin.py

[admin] Removed OrganizationOwner inline because not used #39

---

.travis.yml
openwisp_users/admin.py

[deps] Added support for django 2.2

---

openwisp_users/admin.py

**Blocked:  https://github.com/openwisp/openwisp-utils/pull/62**

[WIP][enhancement] Adding new admin_site

---

.travis.yml
requirements-test.txt
runcheckmigration
runisort

Replace old qa checks with `openwisp-utils-qa-checks` (related to openwisp/openwisp-utils#63 for this repo)

[qa] Replace with openwisp-utils-qa-checks

---

openwisp_users/admin.py
openwisp_users/templates/admin/action_confirmation.html
openwisp_users/tests/test_admin.py

[admin] Add possibility to deactivate users in batch operation

---

.travis.yml
openwisp_users/accounts/urls.py
openwisp_users/admin.py
openwisp_users/migrations/0001_initial.py
openwisp_users/migrations/0002_auto_20180508_2017.py
openwisp_users/migrations/0003_default_organization.py
openwisp_users/migrations/0004_default_groups.py
openwisp_users/migrations/0005_user_phone_number.py
openwisp_users/migrations/0006_id_email_index_together.py
openwisp_users/migrations/0007_unique_email.py
openwisp_users/migrations/__init__.py
openwisp_users/mixins.py
openwisp_users/models.py
openwisp_users/multitenancy.py
openwisp_users/tests/test_admin.py
openwisp_users/tests/test_models.py
openwisp_users/tests/utils.py
run-qa-checks
runtests.py
setup.cfg
setup.py
tests/local_settings.example.py
tests/settings.py
tests/testapp/__init__.py
tests/testapp/admin.py
tests/testapp/migrations/0001_initial.py
tests/testapp/migrations/0002_config_template.py
tests/testapp/migrations/0003_multitenancy.py
tests/testapp/models.py
tests/testapp/test_multitenancy.py

[qa] Minor improvements

---

README.rst

 [docs] Basic API instructions #114

---

README.rst

remove all the lines as mentioned in issue.

 Removed redundant steps for installing for development

---

.travis.yml
requirements-test.txt
requirements.txt

[setup] Require openwisp-utils~=0.5[rest] #119

---

openwisp_users/api/urls.py

[bug] API urls raise exception #126

---

openwisp_users/admin.py
openwisp_users/migrations/0008_update_admins_permissions.py
openwisp_users/migrations/__init__.py
openwisp_users/tests/test_admin.py
tests/openwisp2/sample_users/migrations/0003_update_admins_permissions.py

Fixed the issue by adding a has_delete_permission to
UserAdmin which returns true when the necessary
conditions are met. I Also updated the Administrators'
default permissions by adding email permissions to it
Fixes #128

[admin] Allow administrators to delete other users #128

---

.gitignore
openwisp_users/admin.py
openwisp_users/tests/test_admin.py

Fixed the problem by updating the User
Creation form and also added a clean
method to user change form to validate
that a group must be selected for a staff
which Fixes #103
Fixes #129

[admin] Update UserCreationForm #129

---

CHANGES.rst
openwisp_users/admin.py
openwisp_users/base/models.py
openwisp_users/templates/admin/openwisp_users/user/change_form.html
openwisp_users/tests/test_admin.py

Closed issued by updating the change_permissions
of UserAdmin, OrganizationUserInline and
EmailAddressInline to meet the required needs.
Fixes #132

[admin] Make organization owner read-only #132

---

openwisp_users/admin.py
openwisp_users/tests/test_admin.py

[admin] Remove org owner from organization add form #149

---

openwisp_users/admin.py
openwisp_users/tests/test_admin.py

Closed issue by optimizing organization membership check
with organization membership helpers.
Fixes #142

[admin] Switch to organization membership helpers #142

---

README.rst
openwisp_users/api/permissions.py
openwisp_users/tests/test_api/__init__.py
runtests.py
tests/openwisp2/urls.py
tests/testapp/tests/mixins.py
tests/testapp/tests/test_multitenancy.py
tests/testapp/tests/test_permission_classes.py
tests/testapp/tests/tests.py
tests/testapp/urls.py
tests/testapp/views.py

[multitenancy] Organization Membership validators #150

---

openwisp_users/apps.py

- simplified condition: just check if another org owner exists
- catch also IntegrityError (rare, but can happen)

[chores] Improved create_organization_owner

---

CHANGES.rst
openwisp_users/__init__.py

- [test] Added functions to add inline fields in extended app's integration testing
- [chores] Improved create_organization_owner
Signed-off-by: Ajay Tripathi <ajay39in@gmail.com>

0.3.1 release

---

openwisp_users/tests/test_admin.py

Replaced hard coded inline parameters with `add_user_inline_params`

[refactor] Refactored hard coded tests

---

README.rst
openwisp_users/admin.py
openwisp_users/tests/test_admin.py

Fixed issue by ensuring organization user which belongs to an owner
is deleted.
Fixes #165

[fix] Deleting an OrganizationUser instance may raise exception #165

---

CHANGES.rst
README.rst
openwisp_users/admin.py
openwisp_users/migrations/0001_initial.py
openwisp_users/migrations/0002_auto_20180508_2017.py
openwisp_users/migrations/0003_default_organization.py
openwisp_users/migrations/0004_default_groups.py
openwisp_users/migrations/0005_user_phone_number.py
openwisp_users/migrations/0006_id_email_index_together.py
openwisp_users/migrations/0007_unique_email.py
openwisp_users/migrations/0008_update_admins_permissions.py
openwisp_users/migrations/0009_create_organization_owners.py
openwisp_users/migrations/0010_allow_admins_change_organization.py
openwisp_users/migrations/0011_user_first_name_150_max_length.py
openwisp_users/migrations/__init__.py
openwisp_users/settings.py
openwisp_users/tests/test_admin.py
openwisp_users/tests/test_models.py
tests/openwisp2/sample_users/admin.py
tests/openwisp2/sample_users/migrations/0001_initial.py
tests/openwisp2/sample_users/migrations/0002_default_groups_and_permissions.py
tests/openwisp2/settings.py
tests/testapp/migrations/0001_initial.py
tests/testapp/migrations/0002_config_template.py
tests/testapp/migrations/0003_multitenancy.py
tests/testapp/urls.py

[chores] Fixed typographical error in organization name #173

---

openwisp_users/admin.py
openwisp_users/templates/admin/action_confirmation.html

Cleanup of make active/inactive action.

[chores] Cleanup of make active/inactive action

---

README.rst

Fixes #187
Fixed several broken(return 404) links in Extend openwisp-users.

[Fix] Fixed several broken links in Extend openwisp-users section #187

---

openwisp_users/apps.py
requirements-test.txt
requirements.txt

Blocked by https://github.com/openwisp/openwisp-utils/pull/152

 [deps] Update to openwisp-utils 0.7

---

openwisp_users/api/swagger.py
openwisp_users/api/views.py

[fix] Allow swagger to show parameters of obtain token view #116

---

CHANGES.rst
openwisp_users/__init__.py
requirements-test.txt
requirements.txt

Release 0.5.0

---

openwisp_users/accounts/templates/account/base.html
requirements.txt

[deps] Add support for django-allauth 0.43.0

---

README.rst
openwisp_users/backends.py
openwisp_users/tests/test_admin.py
openwisp_users/tests/test_backends.py
tests/openwisp2/sample_users/tests.py
tests/openwisp2/settings.py

[feature] Allow authenticating with email and phone number #206

---

README.rst
openwisp_users/api/filters.py
openwisp_users/api/mixins.py
tests/testapp/serializers.py
tests/testapp/tests/test_filter_classes.py
tests/testapp/urls.py
tests/testapp/views.py

[feature] Add API filter mixins #210

---

.github/workflows/ci.yml
openwisp_users/admin.py

[deps] Dropped Django 2.2 support

---

openwisp_users/tests/test_admin.py

Used redirect_any_output to remove noisy output instead of devnull.

[fix] Fixed I/O on closed stream error

---

README.rst
openwisp_users/api/mixins.py
tests/testapp/serializers.py
tests/testapp/tests/test_filter_classes.py
tests/testapp/urls.py
tests/testapp/views.py

Restrict Non-Super users from
setting objects to organization=None
Closes #235

[fix] Restrict who can set objects to Organization=None #235

---

README.rst
openwisp_users/api/mixins.py
tests/testapp/migrations/0003_multitenancy.py
tests/testapp/models.py
tests/testapp/serializers.py
tests/testapp/tests/test_filter_classes.py

[fix] Include shared objects while filtering serilaizer fields #247

---

openwisp_users/api/mixins.py
tests/testapp/serializers.py
tests/testapp/tests/test_filter_classes.py
tests/testapp/urls.py
tests/testapp/views.py

[fix] Fixed `KeyError` in `FilterSerializerByOrgManaged` #259

---

openwisp_users/accounts/templates/account/base.html
openwisp_users/apps.py
openwisp_users/tests/test_admin.py
requirements.txt
tests/openwisp2/settings.py

Registered menu groups. This change is needed because ``controller`` is using both ``utils`` and ``users`` but ``users`` is using master branch of ``utils``. I will make changes in the others modules using this PR branch.
closes #253

[enhancement] Registered menu groups #253

---

openwisp_users/accounts/templates/account/base.html

@nemesisdesign I have fixed the template issue for the account page.
**Depends on**
https://github.com/openwisp/openwisp-utils/pull/226

[fix] Fixed account theme

---

openwisp_users/tests/test_admin.py

[fix] Fixed breaking to tests due to new filter #272

---

tests/openwisp2/settings.py

Fix test app not loading local settings.

Fix local_settings in tests app

---

openwisp_users/api/mixins.py
tests/testapp/serializers.py
tests/testapp/tests/test_filter_classes.py
tests/testapp/urls.py
tests/testapp/views.py

[fix] Fixed `NoneType` attribute error raised by filtering mixin #268

---

openwisp_users/tests/test_admin.py

Updated test to compensate for the change in https://github.com/openwisp/openwisp-utils/pull/241.
closes https://github.com/openwisp/openwisp-utils/issues/251

[test] Minor changes in test to fix test failure

---

README.rst
openwisp_users/accounts/templates/account/email_verification_success.html
openwisp_users/accounts/urls.py
openwisp_users/tests/test_models.py
tests/openwisp2/settings.py

[feature] Added email verification success view #277

---

requirements-test.txt
requirements.txt

django-allauth~=0.46.0
django-phonenumber-field~=6.0.0
django-redis~=5.0.0

[change] Updated dependencies

---

tests/openwisp2/settings.py

[chores] Added OPENWISP_USERS_ORGANIZATIONINVITATION_MODEL in settings.py

---

openwisp_users/api/mixins.py
openwisp_users/api/views.py

Added additional check of `if not self.request.user.is_anonymous` so that opening API Docs doesn't throw error.
Fixes #291

[Fix]REST API errors while opening API Docs

---

openwisp_users/migrations/0018_allow_operator_view_organisation.py
openwisp_users/migrations/__init__.py
openwisp_users/tests/test_api/test_api.py
tests/openwisp2/sample_users/migrations/0004_default_groups.py

[fix] Add permission to view org to operator

---

README.rst

- improved explanation of multitenant_shared_relations
- added explanation of multitenant_parent
Closes #58

[docs] Improved MultitenantAdminMixin description #58

---

CHANGES.rst
README.rst
openwisp_users/__init__.py
requirements-test.txt
requirements.txt

The changelog does not include following commits, because some of were trivial or changes (fixes) to a feature that was added in this release. 
List of commits that were not directly (referenced) in the changelog:

1.0.0 release

---

requirements.txt

Needed for `ACCOUNT_PREVENT_ENUMERATION`.

[deps] Bumped django-allauth from ~=0.46.0 to ~=0.50.0

---

openwisp_users/admin.py
openwisp_users/base/models.py
openwisp_users/tests/test_models.py

[change] Added autocomplete fields in OrganizatinOwner admin #325

---

openwisp_users/apps.py
openwisp_users/base/models.py

[enhancement] Added method to invalidate user organization cache #322

---

.coveragerc
.github/workflows/ci.yml

Trying to run tests in parallel to see if we can speed up the CI.

[ci] Run tests in parallel

---

requirements-test.txt
tests/testapp/tests/mixins.py
tests/testapp/tests/test_selenium.py

Similar to : https://github.com/openwisp/openwisp-network-topology/pull/187

[deps] Upgraded selenium

---

openwisp_users/api/mixins.py
tests/testapp/tests/test_filter_classes.py
tests/testapp/views.py

[fix] Fixed related org field filtering in multitentant dj-filters

---

.github/workflows/ci.yml
openwisp_users/__init__.py
requirements-test.txt
requirements.txt
tests/openwisp2/sample_users/__init__.py
tests/openwisp2/sample_users/apps.py
tests/testapp/tests/mixins.py
tests/testapp/tests/test_selenium.py

- Dropped support for Django 4.0.0
- Bumped django-organizations~=2.1.0
- Bumped django-extensions~=3.2.2
- Bumped django-allauth~=0.54.0
- Bumped django-phonenumber-field~=6.1.0
Closes https://github.com/openwisp/openwisp-users/issues/348
------------
**Depends on**

[deps] Added support for Django 4.1.0 and 4.2.0 #348

---

openwisp_users/tests/test_models.py

[fix] Fixed date formatting in test_password_expiration_mail #367

---

README.rst
openwisp_users/api/serializers.py
openwisp_users/tests/test_api/test_api.py

Allow creating users with a verified email via REST API.

[feature:api] Allow creating users with a verified email via REST API

---

openwisp_users/tests/test_models.py

[fix:tests] Fixed expiration mail flaky tests #375

---

openwisp_users/middleware.py
openwisp_users/tests/test_accounts.py

[fix] Allow password expired users to access password reset form #378

---

openwisp_users/admin.py
openwisp_users/tests/test_admin.py

[fix] Admin actions require model permissions

---

tests/testapp/tests/test_filter_classes.py

Added support for djangorestframework<=3.15.1

[deps] Added support for djangorestframework<=3.15.1

---

.github/workflows/pypi.yml

[ci] Added workflow for PyPI publishing

---

.github/workflows/version-branch.yml
CHANGES.rst
openwisp_users/__init__.py
requirements-test.txt
requirements.txt

[ci] Added GitHub workflow to replicate commits to version branch
